#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("TeslaSCAN.Resource", IsApplication=true)]

namespace TeslaSCAN
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010000
			public const int layoutManager = 2130771968;
			
			// aapt resource value: 0x7f010002
			public const int reverseLayout = 2130771970;
			
			// aapt resource value: 0x7f010001
			public const int spanCount = 2130771969;
			
			// aapt resource value: 0x7f010003
			public const int stackFromEnd = 2130771971;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f040003
			public const int directory_item_height = 2130968579;
			
			// aapt resource value: 0x7f040000
			public const int item_touch_helper_max_drag_scroll_per_frame = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int item_touch_helper_swipe_escape_max_velocity = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int item_touch_helper_swipe_escape_velocity = 2130968578;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ProgressStyle = 2130837505;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050007
			public const int ProgressBar1 = 2131034119;
			
			// aapt resource value: 0x7f05000d
			public const int RelativeLayout1 = 2131034125;
			
			// aapt resource value: 0x7f05000f
			public const int StatusText = 2131034127;
			
			// aapt resource value: 0x7f05000c
			public const int arcView1 = 2131034124;
			
			// aapt resource value: 0x7f050019
			public const int bigger = 2131034137;
			
			// aapt resource value: 0x7f050021
			public const int blank = 2131034145;
			
			// aapt resource value: 0x7f050023
			public const int bluetoothEnabled = 2131034147;
			
			// aapt resource value: 0x7f050015
			public const int bottom = 2131034133;
			
			// aapt resource value: 0x7f050026
			public const int browse = 2131034150;
			
			// aapt resource value: 0x7f050016
			public const int copy = 2131034134;
			
			// aapt resource value: 0x7f050018
			public const int debugLog = 2131034136;
			
			// aapt resource value: 0x7f050013
			public const int delete = 2131034131;
			
			// aapt resource value: 0x7f05001f
			public const int deletetab = 2131034143;
			
			// aapt resource value: 0x7f050022
			public const int device = 2131034146;
			
			// aapt resource value: 0x7f050001
			public const int gridLayout1 = 2131034113;
			
			// aapt resource value: 0x7f05000e
			public const int gridView1 = 2131034126;
			
			// aapt resource value: 0x7f050028
			public const int help = 2131034152;
			
			// aapt resource value: 0x7f050012
			public const int item1 = 2131034130;
			
			// aapt resource value: 0x7f050000
			public const int item_touch_helper_previous_elevation = 2131034112;
			
			// aapt resource value: 0x7f050017
			public const int logFast = 2131034135;
			
			// aapt resource value: 0x7f050010
			public const int menuIcon = 2131034128;
			
			// aapt resource value: 0x7f050024
			public const int metric = 2131034148;
			
			// aapt resource value: 0x7f050005
			public const int new_devices = 2131034117;
			
			// aapt resource value: 0x7f05001e
			public const int newtab = 2131034142;
			
			// aapt resource value: 0x7f05001c
			public const int newtrip = 2131034140;
			
			// aapt resource value: 0x7f050003
			public const int paired_devices = 2131034115;
			
			// aapt resource value: 0x7f050020
			public const int paste = 2131034144;
			
			// aapt resource value: 0x7f050011
			public const int prefIcon = 2131034129;
			
			// aapt resource value: 0x7f050006
			public const int relativeLayout1 = 2131034118;
			
			// aapt resource value: 0x7f050025
			public const int resettabs = 2131034149;
			
			// aapt resource value: 0x7f050027
			public const int resetthrow = 2131034151;
			
			// aapt resource value: 0x7f05001d
			public const int resettrip = 2131034141;
			
			// aapt resource value: 0x7f05001a
			public const int smaller = 2131034138;
			
			// aapt resource value: 0x7f050008
			public const int textView1 = 2131034120;
			
			// aapt resource value: 0x7f050009
			public const int textView2 = 2131034121;
			
			// aapt resource value: 0x7f05000a
			public const int textView3 = 2131034122;
			
			// aapt resource value: 0x7f05000b
			public const int textView4 = 2131034123;
			
			// aapt resource value: 0x7f050004
			public const int title_new_devices = 2131034116;
			
			// aapt resource value: 0x7f050002
			public const int title_paired_devices = 2131034114;
			
			// aapt resource value: 0x7f050014
			public const int top = 2131034132;
			
			// aapt resource value: 0x7f05001b
			public const int viewType = 2131034139;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int BatteryLayout = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int device_list = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int device_name = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int ListItem = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int ListItem2 = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int ListItem3 = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int ListItemBattery = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int ListItemGauge = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int Main = 2130903048;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f080000
			public const int AdapterMenu = 2131230720;
			
			// aapt resource value: 0x7f080001
			public const int ContextMenu = 2131230721;
			
			// aapt resource value: 0x7f080002
			public const int main = 2131230722;
			
			// aapt resource value: 0x7f080003
			public const int OptionsMenu = 2131230723;
			
			// aapt resource value: 0x7f080004
			public const int TabsMenu = 2131230724;
			
			// aapt resource value: 0x7f080005
			public const int Wrench = 2131230725;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060000
			public const int app_name = 2131099648;
			
			// aapt resource value: 0x7f060009
			public const int bt_not_enabled_leaving = 2131099657;
			
			// aapt resource value: 0x7f060013
			public const int button_scan = 2131099667;
			
			// aapt resource value: 0x7f060006
			public const int cancel = 2131099654;
			
			// aapt resource value: 0x7f060014
			public const int connect = 2131099668;
			
			// aapt resource value: 0x7f060003
			public const int create_directory = 2131099651;
			
			// aapt resource value: 0x7f060015
			public const int discoverable = 2131099669;
			
			// aapt resource value: 0x7f060001
			public const int intro_message = 2131099649;
			
			// aapt resource value: 0x7f060010
			public const int none_found = 2131099664;
			
			// aapt resource value: 0x7f06000f
			public const int none_paired = 2131099663;
			
			// aapt resource value: 0x7f060008
			public const int not_connected = 2131099656;
			
			// aapt resource value: 0x7f060005
			public const int ok = 2131099653;
			
			// aapt resource value: 0x7f060002
			public const int open_directory = 2131099650;
			
			// aapt resource value: 0x7f06000d
			public const int scanning = 2131099661;
			
			// aapt resource value: 0x7f06000e
			public const int select_device = 2131099662;
			
			// aapt resource value: 0x7f060004
			public const int selected_directory = 2131099652;
			
			// aapt resource value: 0x7f060007
			public const int send = 2131099655;
			
			// aapt resource value: 0x7f06000b
			public const int title_connected_to = 2131099659;
			
			// aapt resource value: 0x7f06000a
			public const int title_connecting = 2131099658;
			
			// aapt resource value: 0x7f06000c
			public const int title_not_connected = 2131099660;
			
			// aapt resource value: 0x7f060012
			public const int title_other_devices = 2131099666;
			
			// aapt resource value: 0x7f060011
			public const int title_paired_devices = 2131099665;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070000
			public const int DirectoryEntryNameFont = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int Theme_Custom = 2131165185;
			
			// aapt resource value: 0x7f070002
			public const int Theme_Custom1 = 2131165186;
			
			// aapt resource value: 0x7f070003
			public const int Theme_Custom2 = 2131165187;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] RecyclerView = new int[] {
					16842948,
					2130771968,
					2130771969,
					2130771970,
					2130771971};
			
			// aapt resource value: 0
			public const int RecyclerView_android_orientation = 0;
			
			// aapt resource value: 1
			public const int RecyclerView_layoutManager = 1;
			
			// aapt resource value: 3
			public const int RecyclerView_reverseLayout = 3;
			
			// aapt resource value: 2
			public const int RecyclerView_spanCount = 2;
			
			// aapt resource value: 4
			public const int RecyclerView_stackFromEnd = 4;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
